# Generated by Django 4.2.20 on 2025-05-10 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='job_seekers/', verbose_name='Фотография')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Опыт работы')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Файл резюме')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль соискателя',
                'verbose_name_plural': 'Профили соискателей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='employers/', verbose_name='Логотип компании')),
                ('company_description', models.TextField(blank=True, null=True, verbose_name='Описание компании')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт компании')),
                ('company_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес компании')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон компании')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email компании')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль работодателя',
                'verbose_name_plural': 'Профили работодателей',
                'ordering': ['-created_at'],
            },
        ),
    ]
