[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn employment_project.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "employment_project.settings_production"
